package mes.domain.po;

import java.util.Date;
import lombok.Data;

@Data
public class EquipDowntimeAdmVo {
	
	private String menuAuth;
	private String downtimeIdx;
	private String equipCd;
	private String equipNm;
	private String workOrdNo;
	private String downtimeCd;
	private String downtimeNm;
	private String dayNightCd;
	private String dayNightNm;
	private String startTime;
	private String endTime;
	private String stopTime;
	private String downtimeRegDate;
	private String code1;
	private String code1Nm;
	private String code2;
	private String code3;
	private String code4;
	private String code5;
	private String code6;
	private String code7;
	private String regId;
	private Date regDate;
	private String updId;
	private Date updDate;
	
	private String equipStatus;
	private String code;
	
	private String workTeamCd;
	private String workTeamNm;
	private String mainWorkChargr;
	private String mainWorkChargrNm;
	private String workStartTime;
	private String workEndTime;
	private String workTime;
	private String ordGubun;
	private String ordGubunNm;
	
	private String planDate;
	private String planDateList;
	
	private float workTimeTotal;
	private float workTime1;
	private float workTime2;
	private float workTime3;
	private float workTime4;
	private float workTime5;
	private float workTime6;
	private float workTime7;
	private float workTime8;
	private float workTime9;
	private float workTime10;
	private float workTime11;
	private float workTime12;
	private float workTime13;
	private float workTime14;
	private float workTime15;
	private float workTime16;
	private float workTime17;
	private float workTime18;
	private float workTime19;
	private float workTime20;
	private float workTime21;
	private float workTime22;
	private float workTime23;
	private float workTime24;
	private float workTime25;
	private float workTime26;
	private float workTime27;
	private float workTime28;
	private float workTime29;
	private float workTime30;
	private float workTime31;
	
	private double fullWorkTimeTotal;
	private double fullWorkTime1;
	private double fullWorkTime2;
	private double fullWorkTime3;
	private double fullWorkTime4;
	private double fullWorkTime5;
	private double fullWorkTime6;
	private double fullWorkTime7;
	private double fullWorkTime8;
	private double fullWorkTime9;
	private double fullWorkTime10;
	private double fullWorkTime11;
	private double fullWorkTime12;
	private double fullWorkTime13;
	private double fullWorkTime14;
	private double fullWorkTime15;
	private double fullWorkTime16;
	private double fullWorkTime17;
	private double fullWorkTime18;
	private double fullWorkTime19;
	private double fullWorkTime20;
	private double fullWorkTime21;
	private double fullWorkTime22;
	private double fullWorkTime23;
	private double fullWorkTime24;
	private double fullWorkTime25;
	private double fullWorkTime26;
	private double fullWorkTime27;
	private double fullWorkTime28;
	private double fullWorkTime29;
	private double fullWorkTime30;
	private double fullWorkTime31;
	
	private double percentTotal;
	private double percent1;
	private double percent2;
	private double percent3;
	private double percent4;
	private double percent5;
	private double percent6;
	private double percent7;
	private double percent8;
	private double percent9;
	private double percent10;
	private double percent11;
	private double percent12;
	private double percent13;
	private double percent14;
	private double percent15;
	private double percent16;
	private double percent17;
	private double percent18;
	private double percent19;
	private double percent20;
	private double percent21;
	private double percent22;
	private double percent23;
	private double percent24;
	private double percent25;
	private double percent26;
	private double percent27;
	private double percent28;
	private double percent29;
	private double percent30;
	private double percent31;
	
}